name: Check Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run ktlint Check
        run: ./gradlew :p2pml:ktlintCheck

      - name: Build with Gradle
        run: ./gradlew clean build
